name: Release sshproxy

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  release-sshproxy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        targets:
          - OS: darwin
            ARCH: amd64
            EXT: ""
          - OS: darwin
            ARCH: arm64
            EXT: ""
          - OS: windows
            ARCH: amd64
            EXT: .exe
          - OS: windows
            ARCH: arm64
            EXT: .exe
          - OS: linux
            ARCH: amd64
            EXT: ""
          - OS: linux
            ARCH: arm64
            EXT: ""
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23
      - name: Go Build
        run: |
          export CGO_ENABLED=0
          export GOOS=${{ matrix.targets.OS }}
          export GOARCH=${{ matrix.targets.ARCH }}
          mkdir -p dist
          go build \
            -trimpath \
            -ldflags="-s -w" \
            -o dist/sshproxy-${{ matrix.targets.OS }}-${{ matrix.targets.ARCH }}${{ matrix.targets.EXT }} \
            ./sshproxy/cmd/sshproxy.go
      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.targets.OS }}-${{ matrix.targets.ARCH }}
          path: dist/*
      - name: Release
        if: ${{ startsWith(github.ref, 'refs/tags/') }}
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          append_body: false
          fail_on_unmatched_files: true
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: |
            dist/*
